import {z} from 'zod';
import type {DatabaseSync} from 'node:sqlite';
import {deckSchema,type Deck} from '../lib/model';
import {createRepository} from '../lib/repository';
import {imageData,decodeImage,assetPath} from './assets';
import {existsSync,readFileSync,writeFileSync} from 'node:fs';
const changeSchema=z.object({slideId:z.string(),slideTitle:z.string(),field:z.string(),before:z.string(),after:z.string()});
const revisionSchema=z.object({version:z.number().int().positive(),request_id:z.string().min(1).max(100),snapshot:deckSchema,reason:z.string().max(1000),actor:z.string().max(100),at:z.string().max(100),changes:z.array(changeSchema)});
const backupSchema=z.object({format:z.literal('agent-slides-backup-v1'),initial:deckSchema,revisions:z.array(revisionSchema).max(10000),chat:z.array(z.object({role:z.enum(['user','assistant']),text:z.string().max(1000000),at:z.string().max(100)})).default([]),assets:z.record(z.string()).default({})});
function referenced(value:unknown){const result=new Set<string>();function walk(v:unknown){if(!v||typeof v!=="object")return;for(const [key,x] of Object.entries(v)){if(key==='src'&&typeof x==='string'&&/^\/api\/assets\/[a-f0-9-]+\.(png|jpg|webp)$/.test(x))result.add(x);else if(x&&typeof x==='object')walk(x);}}walk(value);return [...result];}
export async function exportBackup(db:DatabaseSync,repo:ReturnType<typeof createRepository>,user:string,id:string){const initial=await repo.restoreSnapshot(user,0,id);const rows=id==='legacy'?db.prepare('SELECT * FROM revisions WHERE owner=? ORDER BY version').all(user):db.prepare('SELECT * FROM deck_revisions WHERE owner=? AND deck_id=? ORDER BY version').all(user,id);const revisions=rows.map(r=>({...r,snapshot:JSON.parse(r.snapshot as string),changes:JSON.parse(r.changes as string)}));const assets=Object.fromEntries(referenced({initial,revisions}).map(src=>[src,imageData(src)]));const chat=db.prepare('SELECT role,text,at FROM chat WHERE deck_id=? ORDER BY rowid').all(id);return {format:'agent-slides-backup-v1',savedAt:new Date().toISOString(),initial,revisions,chat,assets};}
export function importBackup(db:DatabaseSync,user:string,input:unknown){const b=backupSchema.parse(input);if(b.revisions.some((r,i)=>r.version!==i+1)||new Set(b.revisions.map(r=>r.request_id)).size!==b.revisions.length)throw Error('履歴の版番号またはIDが不正です');const images=new Map<string,Buffer>();for(const [src,data]of Object.entries(b.assets)){const path=assetPath(src),decoded=decodeImage(data);if(!src.endsWith('.'+decoded.ext))throw Error('画像の拡張子が一致しません');if(existsSync(path)&&!readFileSync(path).equals(decoded.bytes))throw Error('同名の画像が異なります。元のデータは変更しません');images.set(path,decoded.bytes);}for(const src of referenced({initial:b.initial,revisions:b.revisions})){if(!images.has(assetPath(src))&&!existsSync(assetPath(src)))throw Error('バックアップに必要な画像がありません');}
 const id=crypto.randomUUID();db.exec('BEGIN IMMEDIATE');try{for(const [path,bytes]of images)if(!existsSync(path))writeFileSync(path,bytes);db.prepare('INSERT INTO decks(owner,id,snapshot,created_at) VALUES(?,?,?,?)').run(user,id,JSON.stringify(b.initial),new Date().toISOString());const stmt=db.prepare('INSERT INTO deck_revisions(owner,deck_id,version,request_id,snapshot,reason,actor,at,changes) VALUES(?,?,?,?,?,?,?,?,?)');for(const r of b.revisions)stmt.run(user,id,r.version,r.request_id,JSON.stringify(r.snapshot),r.reason,r.actor,r.at,JSON.stringify(r.changes));for(const c of b.chat)db.prepare('INSERT INTO chat VALUES(?,?,?,?)').run(id,c.role,c.text,c.at);db.exec('COMMIT');return {id};}catch(e){db.exec('ROLLBACK');throw e;}}
