'use client';
import {useRef,useState,useLayoutEffect,type CSSProperties} from 'react';
import {type SlideObject,type TextStyle,safeLink} from '@/lib/objects';
import {ImportedChart} from './imported-chart';
import {MotionArt} from './motion-art';
export function textCss(s:TextStyle={}):CSSProperties{return {fontFamily:s.fontFamily,fontSize:s.fontSize?`${s.fontSize/12}cqw`:undefined,fontWeight:s.bold===undefined?undefined:s.bold?700:400,fontStyle:s.italic?'italic':undefined,textDecoration:s.underline?'underline':undefined,color:s.color,textAlign:s.align,lineHeight:s.lineHeight};}
export const chartColors=['#2454ef','#13a89e','#ef8244','#b26de3','#e0507a','#71819a'];
export function ObjectChart({object:o}:{object:SlideObject}){
 if(o.chartFormat&&o.chartType!=='pie')return <ImportedChart object={o}/>;
 const rows=o.cells.slice(1),series=o.cells[0]?.slice(1)||[],values=rows.map(r=>r.slice(1).map(Number));const flat=values.flat();const max=Math.max(0,...flat),min=Math.min(0,...flat),range=max-min||1;
 const y=(n:number)=>270-(n-min)/range*230,base=y(0),cw=440/Math.max(rows.length,1);const total=values.reduce((sum,r)=>sum+Math.max(0,r[0]||0),0);let angle=-Math.PI/2;
 return <svg viewBox="0 0 560 350" width="100%" height="100%" role="img" aria-label={`${o.chartType} グラフ`}>
 {o.chartType==='pie'?<>{total?values.map((v,i)=>{const a=angle;angle+=Math.max(0,v[0])/total*Math.PI*2;const end=angle;const point=(n:number)=>`${170+105*Math.cos(n)},${160+105*Math.sin(n)}`;return <g key={i}>{end-a>=Math.PI*2-.001?<circle cx="170" cy="160" r="105" fill={chartColors[i%6]}/>:<path d={`M170,160 L${point(a)} A105,105 0 ${end-a>Math.PI?1:0},1 ${point(end)} Z`} fill={chartColors[i%6]}/>}<rect x="310" y={40+i*24} width="12" height="12" fill={chartColors[i%6]}/><text x="330" y={51+i*24} fontSize="13" fill="currentColor">{rows[i][0]}: {v[0]}</text></g>}):<text x="80" y="165" fill="currentColor">正の数値を入力してください</text>}</>:<>
 {[0,1,2,3,4].map(i=><g key={i}><line x1="70" x2="510" y1={40+i*57.5} y2={40+i*57.5} stroke="#94a3b8" opacity=".25"/><text x="60" y={45+i*57.5} textAnchor="end" fontSize="12" fill="currentColor">{(max-i*range/4).toLocaleString(undefined,{maximumFractionDigits:1})}</text></g>)}
 {series.map((name,j)=><g key={j}>{o.chartType==='line'?<><polyline fill="none" stroke={chartColors[j%6]} strokeWidth="3" points={values.map((v,i)=>`${70+cw*(i+.5)},${y(v[j])}`).join(' ')}/>{values.map((v,i)=><circle key={i} cx={70+cw*(i+.5)} cy={y(v[j])} r="4" fill={chartColors[j%6]}/>)}</>:values.map((v,i)=><rect key={i} x={70+cw*i+cw*.1+j*cw*.8/series.length} y={Math.min(base,y(v[j]))} width={cw*.8/series.length} height={Math.max(1,Math.abs(base-y(v[j])))} fill={chartColors[j%6]}/>)}<rect x={70+j*100} y="323" width="10" height="10" fill={chartColors[j%6]}/><text x={84+j*100} y="332" fontSize="12" fill="currentColor">{name}</text></g>)}
 {rows.map((r,i)=><text key={i} x={70+cw*(i+.5)} y="294" textAnchor="middle" fontSize="12" fill="currentColor">{r[0]}</text>)}
 </>}
 </svg>;
}
function ObjectBody({object:o,editing,inspect=false,linksActive=false,onText}:{object:SlideObject;editing:boolean;inspect?:boolean;linksActive?:boolean;onText:(text:string)=>void}){
 const ref=useRef<HTMLDivElement>(null);const [overflow,setOverflow]=useState(false);
 // 編集モードへの切り替え時に入力先も移し、Deleteが要素削除に流れないようにする。
 useLayoutEffect(()=>{if(editing)ref.current?.querySelector<HTMLElement>('[data-object-text]')?.focus();},[editing]);
 useLayoutEffect(()=>{const el=ref.current;if(!el)return;if(o.kind!=='text'&&o.kind!=='table'){setOverflow(false);return;}const measure=()=>setOverflow(el.scrollHeight>el.clientHeight+2||el.scrollWidth>el.clientWidth+2);measure();const ro=new ResizeObserver(measure);ro.observe(el);return()=>ro.disconnect();},[o]);
 return <div ref={ref} data-text-overflow={overflow?"true":undefined} className={`free-object-body ${overflow&&inspect?'text-overflow':''}`} style={{...textCss(o.style),width:'100%',height:'100%',overflow:'hidden',...(o.kind==='text'?{display:'flex',flexDirection:'column',justifyContent:o.verticalAlign==='center'?'center':o.verticalAlign==='bottom'?'flex-end':'flex-start'}:{})}}>
 {o.kind==='text'&&<div data-object-text contentEditable={editing?'plaintext-only':false} suppressContentEditableWarning style={{width:'100%',flexShrink:0,whiteSpace:'pre-wrap',outline:0}} onBlur={e=>onText(e.currentTarget.innerText)} onKeyDown={e=>{if(editing)e.stopPropagation();}}>{o.href&&safeLink(o.href)&&!editing?<a href={o.href} target="_blank" rel="noopener noreferrer" style={{color:'inherit',textDecoration:'underline',pointerEvents:linksActive?'auto':'none'}} tabIndex={linksActive?0:-1} onPointerDown={e=>{if(linksActive)e.stopPropagation();}} onClick={e=>{e.stopPropagation();if(!linksActive)e.preventDefault();}}>{o.text}</a>:o.text}</div>}
 {o.kind==='image'&&<img alt={o.name} draggable={false} src={o.src} style={{width:'100%',height:'100%',objectFit:o.fit,objectPosition:`${o.cropX}% ${o.cropY}%`}}/>}
 {o.kind==='shape'&&<svg width="100%" height="100%" viewBox="0 0 100 100" preserveAspectRatio="none" style={{overflow:'visible'}}><g fillOpacity={o.fillOpacity ?? 1} strokeWidth={o.strokeWidth===undefined?1:o.strokeWidth/Math.max(o.w,o.h)*100}>{o.shape==='ellipse'?<ellipse cx="50" cy="50" rx="48" ry="48" fill={o.fill} stroke={o.stroke}/>:o.shape==='line'?<line x1="0" y1="50" x2="100" y2="50" strokeWidth={o.strokeWidth===undefined?2:o.strokeWidth/o.h*100} stroke={o.stroke}/>:o.shape==='arrow'?<path d="M0 35H65V10L100 50 65 90V65H0Z" fill={o.fill} stroke={o.stroke}/>:<rect x="1" y="1" width="98" height="98" rx="0" fill={o.fill} stroke={o.stroke}/>}</g></svg>}
 {o.kind==='table'&&<table className="object-table" style={{fontSize:o.style.fontSize?`${o.style.fontSize/12}cqw`:'1.4cqw'}}><tbody>{o.cells.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j} style={i===0?{background:o.fill,fontWeight:700}:undefined}>{v}</td>)}</tr>)}</tbody></table>}
 {o.kind==='chart'&&<ObjectChart object={o}/>}
 {o.kind==='motion'&&o.customSvg&&<img alt={o.name} src={'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(o.customSvg)} style={{width:'100%',height:'100%',objectFit:'contain'}}/>}
 {o.kind==='motion'&&!o.customSvg&&<div style={{width:'100%',height:'100%','--art-color':o.fill,'--orbit-duration':`${o.duration}s`} as CSSProperties}><MotionArt kind={o.motion} strokeWidth={o.strokeWidth}/></div>}
 {overflow&&inspect&&<span className="overflow-badge">文字が枠を超えています</span>}
 </div>;
}
export function FreeObjects({objects,editable=false,linksActive=false,selected=[],onSelect,onChange,onBegin}:{objects:SlideObject[];editable?:boolean;linksActive?:boolean;selected?:string[];onSelect?:(ids:string[])=>void;onChange?:(objects:SlideObject[])=>void;onBegin?:()=>void}){
 const root=useRef<HTMLDivElement>(null);const drag=useRef<{x:number;y:number;objects:SlideObject[];ids:string[];scale:number;resize:boolean;id:string}|null>(null);const [textId,setTextId]=useState('');const [guide,setGuide]=useState<{x?:number;y?:number}>({});
 const update=(id:string,patch:Partial<SlideObject>)=>onChange?.(objects.map(o=>o.id===id?{...o,...patch}:o));
 return <div ref={root} className="free-objects" style={{pointerEvents:'none'}}>
 {objects.filter(o=>!o.hidden).map(o=><div key={o.id} data-free-object={o.id} data-kind={o.kind} className={`free-object ${editable&&selected.includes(o.id)?'object-selected':''}`} tabIndex={editable?0:undefined} role={editable?'group':undefined} aria-label={o.name} style={{left:`${o.x/16}%`,top:`${o.y/9}%`,width:`${o.w/16}%`,height:`${o.h/9}%`,transform:`rotate(${o.rotation}deg)`,opacity:o.opacity,pointerEvents:editable?'auto':'none',cursor:editable&&!o.locked?'move':undefined}}
 onDoubleClick={e=>{if(editable&&o.kind==='text'&&!o.locked){e.stopPropagation();setTextId(o.id);}}}
 onPointerDown={e=>{if(!editable||textId===o.id)return;e.stopPropagation();e.preventDefault();let ids=selected.includes(o.id)?selected:[o.id];if(e.shiftKey||e.metaKey){ids=selected.includes(o.id)?selected.filter(id=>id!==o.id):[...selected,o.id];}else if(o.groupId)ids=objects.filter(x=>x.groupId===o.groupId).map(x=>x.id);onSelect?.(ids);e.currentTarget.focus();setTextId('');if(o.locked)return;onBegin?.();const r=root.current!.getBoundingClientRect();drag.current={x:e.clientX,y:e.clientY,objects:structuredClone(objects),ids:ids.filter(id=>!objects.find(x=>x.id===id)?.locked),scale:1600/r.width,resize:(e.target as HTMLElement).dataset.objectResize==='true',id:o.id};e.currentTarget.setPointerCapture(e.pointerId);}}
 onPointerMove={e=>{const d=drag.current;if(!d)return;let dx=(e.clientX-d.x)*d.scale,dy=(e.clientY-d.y)*d.scale;const source=d.objects.find(x=>x.id===d.id)!;setGuide({});if(!d.resize&&!e.altKey){const targets=d.objects.filter(x=>!d.ids.includes(x.id)&&!x.hidden);const xs=[0,800,1600,...targets.flatMap(x=>[x.x,x.x+x.w/2,x.x+x.w])],ys=[0,450,900,...targets.flatMap(x=>[x.y,x.y+x.h/2,x.y+x.h])];let gx,gy;for(const x of xs){const match=[source.x+dx,source.x+source.w/2+dx,source.x+source.w+dx].find(v=>Math.abs(v-x)<8);if(match!==undefined){dx+=x-match;gx=x;break;}}for(const y of ys){const match=[source.y+dy,source.y+source.h/2+dy,source.y+source.h+dy].find(v=>Math.abs(v-y)<8);if(match!==undefined){dy+=y-match;gy=y;break;}}setGuide({x:gx,y:gy});}onChange?.(d.objects.map(x=>d.ids.includes(x.id)?d.resize?{...x,w:Math.min(3200,Math.max(20,x.w+dx)),h:Math.min(1800,Math.max(20,x.h+(e.shiftKey?dx*x.h/x.w:dy)))}:{...x,x:Math.max(-1600,Math.min(3200,x.x+dx)),y:Math.max(-900,Math.min(1800,x.y+dy))}:x));}}
 onPointerUp={e=>{drag.current=null;setGuide({});if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}}
 onPointerCancel={()=>{drag.current=null;setGuide({});}}
 onKeyDown={e=>{if(!editable||textId===o.id)return;if(['Delete','Backspace','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();e.stopPropagation();onBegin?.();const ids=selected.includes(o.id)?selected:[o.id];if(e.key==='Delete'||e.key==='Backspace'){onChange?.(objects.filter(x=>!ids.includes(x.id)||x.locked));return;}onChange?.(objects.map(x=>ids.includes(x.id)&&!x.locked?{...x,x:Math.max(-1600,Math.min(3200,x.x+(e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0)*(e.shiftKey?10:1))),y:Math.max(-900,Math.min(1800,x.y+(e.key==='ArrowDown'?1:e.key==='ArrowUp'?-1:0)*(e.shiftKey?10:1)))}:x));}}}>
 <ObjectBody linksActive={linksActive} object={o} inspect={editable} editing={editable&&textId===o.id&&!o.locked} onText={text=>{update(o.id,{text});setTextId('');}}/>
 {editable&&selected.includes(o.id)&&<><span className="object-name">{o.name}{o.locked?' 🔒':''}</span>{!o.locked&&<span data-object-resize="true" className="object-resize" aria-label="要素のサイズ変更"/>}</>}
 </div>)}
 {guide.x!==undefined&&<div className="snap-guide vertical" style={{left:`${guide.x/16}%`}}/>}{guide.y!==undefined&&<div className="snap-guide horizontal" style={{top:`${guide.y/9}%`}}/>}
 </div>;
}
