'use client';
import {useDialog} from './use-dialog';
import {useState} from 'react';import {createPortal} from 'react-dom';import {type Deck} from '@/lib/model';import {reviewChanges,mergeReview} from '@/lib/review';import {SlideView} from './studio-client';
export default function ReviewPanel({base,next,onApply,disabled}:{base:Deck;next:Deck;onApply:(d:Deck)=>void;disabled:boolean}){
 const [expanded,setExpanded]=useState(false);
 const dialogRef=useDialog(expanded,()=>setExpanded(false));
 const rows=reviewChanges(base,next);const [ids,setIds]=useState(()=>rows.map(r=>r.id)),[previewId,setPreviewId]=useState(rows.find(r=>r.slideId)?.slideId||next.slides[0].id);let merged:Deck|undefined,error='';try{merged=mergeReview(base,rows,ids);}catch{error='この組合せは適用できません。スライド構成の変更も選択してください。';}const a=base.slides.find(s=>s.id===previewId),b=merged?.slides.find(s=>s.id===previewId);
 const panel=<section ref={dialogRef} className={`visual-review ${expanded?"review-expanded":""}`} role={expanded?"dialog":undefined} aria-modal={expanded||undefined} aria-label="変更の比較" onKeyDown={e=>{if(e.key==="Escape"){e.stopPropagation();setExpanded(false);}}}><button type="button" className="review-expand-toggle" onClick={()=>setExpanded(!expanded)}>{expanded?"比較を閉じる":"大きく比較する"}</button><div className="review-toolbar"><strong>{ids.length} / {rows.length} 件を採用</strong><button type="button" onClick={()=>setIds(rows.map(r=>r.id))}>すべて選択</button><button type="button" onClick={()=>setIds([])}>解除</button></div><label>比較するスライド<select aria-label="比較するスライド" value={previewId} onChange={e=>setPreviewId(e.target.value)}>{[...new Map([...base.slides,...next.slides].map(s=>[s.id,s])).values()].map(s=><option key={s.id} value={s.id}>{s.title||'無題'}</option>)}</select></label><div className="review-previews">{[a,b].map((s,i)=><div key={i}><small>{i?'採用後':'変更前'}</small><div className="review-slide">{s?<SlideView slide={{...s,strokes:[]}} index={0} total={1} animate={false}/>:<span>スライドなし</span>}</div></div>)}</div><div className="review-change-list">{rows.map(r=><label className="review-change" key={r.id}><input type="checkbox" checked={ids.includes(r.id)} onChange={e=>setIds(e.target.checked?[...ids,r.id]:ids.filter(id=>id!==r.id))}/><span><strong>{r.label}</strong><details><summary>変更内容</summary><del>{typeof r.before==='string'?r.before:JSON.stringify(r.before)||'なし'}</del><ins>{typeof r.after==='string'?r.after:JSON.stringify(r.after)||'なし'}</ins></details></span></label>)}</div>{error&&<p role="alert">{error}</p>}<button type="button" className="primary review-apply" disabled={disabled||!ids.length||!merged} onClick={()=>merged&&onApply(merged)}>選択した変更を適用</button></section>;
 return expanded?<>{createPortal(panel,document.body)}</>:panel;
}
